import m1 from "/public/Maroon and White Photo Heavy FaminePoverty Crisis Hub Facebook Post (1).png";
const bestselling = [
  {
    name: "name1",
    photo: m1,
    description: "the first item",
    size: ["40", "41", "42", "43", "44", "45"],
    href: "/shoes/name1",
    price: 500,
  },
  {
    name: "name2",
    photo: m1,
    description: "the secound item",
    size: ["40", "41", "42", "43", "44", "45"],
    href: "/shoes/name2",
    price: 500,
  },
  {
    name: "name3",
    photo: m1,
    description: "the third item",
    size: ["40", "41", "42", "43", "44"],
    href: "/shoes/name3",
    price: 600,
  },
  {
    name: "name4",
    photo: m1,
    description: "the four item",
    size: ["40", "41", "42", "43", "44","45"],
    href: "/shoes/name4",
    price: 600,
  },
  {
    name: "name5",
    photo: m1,
    description: "the five item",
    size: ["40", "41", "42", "43", "44", "45"],
    href: "/shoes/name5",
    price: 700,
  },
  {
    name: "name6",
    photo: m1,
    description: "the sex item",
    size: ["40", "41", "42", "43", "44", "45"],
    href: "/shoes/name6",
    price: 700,
  },
  {
    name: "name7",
    photo: m1,
    description: "the sex item",
    size: ["40", "41", "42", "43", "44", "45"],
    href: "/shoes/name6",
    price: 800,
  },
  {
    name: "name8",
    photo: m1,
    description: "the sex item",
    size: ["40", "41", "42", "43", "44", "45"],
    href: "/shoes/name6",
    price: 800,
  },
  {
    name: "name9",
    photo: m1,
    description: "the sex item",
    size: ["40", "41", "42", "43", "44", "45"],
    href: "/shoes/name6",
    price: 900,
  },
  {
    name: "name10",
    photo: m1,
    description: "the sex item",
    size: ["40", "41", "42", "43", "44", "45"],
    href: "/shoes/name6",
    price: 900,
  },
];
export default bestselling;
